# Generated by Django 5.2.16 on 2026-07-11 14:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customerprofile_producerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per selected unit.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('item', 'Item'), ('kg', 'Kilogram'), ('g', 'Gram'), ('litre', 'Litre'), ('ml', 'Millilitre'), ('dozen', 'Dozen'), ('bunch', 'Bunch'), ('loaf', 'Loaf'), ('jar', 'Jar'), ('pack', 'Pack')], default='item', max_length=20)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('availability_status', models.CharField(choices=[('in_season', 'In Season'), ('year_round', 'Available Year-Round'), ('out_of_season', 'Out of Season'), ('unavailable', 'Unavailable')], default='in_season', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('best_before_date', models.DateField(blank=True, null=True)),
                ('allergen_information', models.TextField(help_text="List all allergens, or enter 'No common allergens'.")),
                ('organic_certified', models.BooleanField(default=False)),
                ('organic_certification_details', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.category')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.producerprofile')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('producer', 'name'), name='unique_product_name_per_producer'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='product_price_greater_than_zero'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='product_stock_not_negative'), models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='product_threshold_not_negative')],
            },
        ),
    ]
