# Generated by Django 5.2.16 on 2026-07-11 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('orders', '0003_producerorderstatushistory_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('new_order', 'New Order'), ('order_status', 'Order Status'), ('low_stock', 'Low Stock')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.product'),
        ),
    ]
